[package]
name = "binanceQ"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = "0.15.0"
binance = { git = "https://github.com/wisespace-io/binance-rs.git" }
serde = "1.0.141"
serde_with = "2.0.1"
env_logger = "0.9.0"
rust_decimal = "1.26.1"
once_cell = "1.16.0"
mongodb = {version = "2.1.0", features = ["sync"], default-features = false}