[package]
name = "binanceQ"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = "0.15.0"
binance = { path = "../opensource/binance-rs" }
serde = "1.0.141"
serde_with = "2.0.1"
env_logger = "0.9.0"
rust_decimal = "1.26.1"
futures = "0.3.25"
async-std = "1.12.0"
once_cell = "1.16.0"
error-chain = "0.12.4"
mongodb = {version = "2.1.0", features = ["sync"], default-features = false}