[package]
name = "binance_q_types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yata = "0.6.1"
rust_decimal = "1.27.0"